### ISSUE TITLE
Correct all references to "cells"

### ISSUE THREAD

**Issue by emhoracek** [emhoracek/smooch#1]
There's always been inconsistencies in the spelling of the term for the basic image unit of a KiSS doll, and at first I was pretty sure it was supposed to be "cell". But looking at the original KiSS spec and considering the origin of the term is from animation (cel or celluloid), I'm now certain "cel" is the correct term and spelling. 

All the references to "cell" or "cells" should be changed to "cel" or "cels".

**Comment by samcwilson** [comment]
Hello.

**Comment by alexanderzafirov** [comment]
Hello! I found this interesting project though the `Hacktoberfest` label. I would like to look at this. 
Just to clarify - is this documentation or code related? Or both :)

**Comment by emhoracek** [comment]
@alexanderzafirov hi! glad to hear. This discrepancy is visible in both the documentation and the code, I think, and I would like it to be fixed in both places.

This is intended to be a ticket for people who are new to contributing to open source, btw -- if that describes you I'm happy to assign the ticket to you.

**Comment by alexanderzafirov** [comment]
Well, I've contributed before but not to this project. Let me give it a shot. Hopefully I can practise my Haskell and Js :)

**Comment by emhoracek** [comment]
@alexanderzafirov I intended this issue to be something like http://www.firsttimersonly.com/ -- I've added that label to make it clearer. Closer to October I'll have lots more Hacktober issues written up and hopefully some of those will be interesting to you! In the meantime, please don't work on this so that a total newbie can take it.

**Comment by vagita24** [comment]
@emhoracek  Can I take this issue?? This can be my second attempt, first attempt you know well.

**Comment by emhoracek** [comment]
@vagita24 sure!

**Comment by AlwinaO** [comment]
Hello, I'd like to claim this issue.

**Comment by emhoracek** [comment]
@AlwinaO It's yours!

**Comment by AlwinaO** [comment]
Hello, I made the first of a number of commits to fix this issue on javascript/doll.js. If this looks good, I will continue with other files. 
Once I finish updating all the files, do I click on a new pull request? Or should I click on a new pull request even though I'm still updating the files?
Thank you in advance for your input!

**Comment by emhoracek** [comment]
Hi @AlwinaO, sorry it took so long to get back to you!

I'm trying to think what the best way to do this would be.

It's always good to make PRs as small as possible while still making sure the PR works as a whole. Sometimes, if you change the spelling in one file, it will break another file. If the backend is outputting "cells" and your javascript is now looking for "cels", that's going to be broken.

So, next could you change *just* this line in the backend:
https://github.com/emhoracek/smooch/blob/master/app/src/Kiss.hs#L46 

and on the frontend change all the occurrences in `doll.js` and 'setdata.js`? 

Make a PR, I'll test it, and then we'll merge it if everything still works.

Sound okay?

**Comment by AlwinaO** [comment]
No worries @emhoracek! I will make sure to do so in the future. 
I will work on this now and make the pull request. 
Thank you for reviewing.

**Comment by emhoracek** [comment]
Yay our oldest issue is RESOLVED 🎉  Thank you @AlwinaO !
