### ISSUE TITLE
"Hikaru, Umi, and Fuu" by Makoto (1994) 

### ISSUE THREAD

**Issue by emhoracek** [emhoracek/smooch#15]
Similar problems to #8, missing backgrounds.

In Smooch:
<img width="657" alt="screen shot 2017-08-15 at 10 12 17 pm" src="https://user-images.githubusercontent.com/5353499/29344590-de41fb5e-8206-11e7-8a31-1b1e78268e9b.png">

In UltraKiSS:
<img width="659" alt="screen shot 2017-08-15 at 10 15 43 pm" src="https://user-images.githubusercontent.com/5353499/29344649-53673304-8207-11e7-9f5e-b18e85aacbf9.png">

On OtakuWorld: http://otakuworld.com/kiss/dolls/pages/k/ksraye_1.htm

**Comment by huggablemonad** [comment]
With this config:

```
(640,400)
%ks_ray.kcf

#0 mokona.cel : 0
#1 bk00.cel : 0

$0 224,350 *
```

In fkiss:

![ksraye_1-background-test](https://user-images.githubusercontent.com/17948023/29394084-bcd58898-833a-11e7-9f0e-b5a916e7aa03.png)

So maybe `*` doesn't always mean a "non-existent object"? I think the background is missing in Smooch because it's getting assigned a value of `NoPosition`.

**Comment by emhoracek** [comment]
WHAT THE HECK

Maybe objects without a specified position are by default positioned at (0,0)? And if the position isn't changed from the default, the viewer assigns it `*`, same as if the object doesn't exist? 

Thanks for doing this detective work!

**Comment by emhoracek** [comment]
I'm going to say this is a bug in the JavaScript because we can just say if there's no position for an object, the position is (0,0).

**Comment by emhoracek** [comment]
Yay, it looks great now! 

<img width="663" alt="screen shot 2017-08-17 at 9 27 53 pm" src="https://user-images.githubusercontent.com/5353499/29440452-ff9ff2dc-8392-11e7-8476-6d82c5f7353c.png">

Thanks again @huggablemonad!
