### ISSUE TITLE
Move "haskell" directory to "app"

### ISSUE THREAD

**Issue by emhoracek** [emhoracek/smooch#22]
It's not clear right now that the actually running app is located in the "haskell" directory. So let's change the name of that directory to "app". 

This task also includes changing the third paragraph of the "structure" section of the README to say "app" instead of "haskell" and fixing the link in the CONTRIBUTING file in the [Backend](https://github.com/emhoracek/smooch/blob/master/CONTRIBUTING.md#backend-haskell) section.

This is a "first-timers-only" task. If you have never contributed to an open source project, you can work on this issue and I will help you through the process. If you've contributed to any OSS project before, please leave this issue for someone else.

**Comment by willshiel** [comment]
Hi!  I was wondering if I could take this? I'm a beginner with contributing to open source projects and would love to partake in hacktoberfest

**Comment by emhoracek** [comment]
@willshiel Sure! Go ahead and fork the project, then make your changes and make a pull request back here. Let me know if you need any help or run into any problems!

**Comment by willshiel** [comment]
Just submitted my pull request.  Should be all good, but let me know if there's anything else I need to do! Thanks!

**Comment by emhoracek** [comment]
@willshiel Looks great -- thanks so much!
