### ISSUE TITLE
Fix imports list in ShellSpec

### ISSUE THREAD

**Issue by emhoracek** [emhoracek/smooch#24]
Very tiny fix!

In every Haskell file, there should be two separate lists of imports. The top list is imports from outside libraries. The bottom list is imports from within the project.

In `haskell/tests/ShellSpec.hs`, `import Shell` is in the top list. Please move it to the bottom list.

This is a "first-timers-only" task. If you have never contributed to an open source project, you can work on this issue and I will help you through the process. If you've contributed to any OSS project before, please leave this issue for someone else.

**Comment by Jorissss** [comment]
Will do! Do I just fork and then send a pull request?

**Comment by emhoracek** [comment]
@Jorissss great! Yes, please fork and make a PR!

**Comment by emhoracek** [comment]
Fixed by #34 ! Thanks for your help!
