### ISSUE TITLE
Link to installation guide?

### ISSUE THREAD

**Issue by lisaychuang** [emhoracek/smooch#32]
Hi Libby,

I'm going through CONTRIBUTING.md, and the first link in [Filing an issue](https://github.com/emhoracek/smooch/blob/master/CONTRIBUTING.md#filing-an-issue) to [get Smooch working on your own computer](https://github.com/emhoracek/smooch/blob/master) is a broken link with 404 error.

I see that there's a section further down the guide to [Run Smooch on your computer](https://github.com/emhoracek/smooch/blob/master/CONTRIBUTING.md#run-smooch-on-your-computer) -- should I just update the link to this section?  Or to create a new file (e.g. install.md)

Thanks!
Lisa

**Comment by lisaychuang** [comment]
An example of a great installation guide, inclued in README.md file is @mike-north's repo: https://github.com/mike-north/vscode-fundamentals/blob/master/README.md

**Comment by emhoracek** [comment]
@lisaychuang Thanks so much! I'm definitely still figuring out how to document stuff so I really appreciate resources like this! I've spent so much time in Haskell -- land of zero documentation -- I've forgotten what good docs look like!

**Comment by emhoracek** [comment]
Fixed by #33
