### ISSUE TITLE
Incorrect item dragged when page is zoomed in or out

### ISSUE THREAD

**Issue by huggablemonad** [emhoracek/smooch#4]
Browser: Vivaldi 1.10.845.3 (32-bit)
OS: Linux

Description: When I try to drag something when the page is zoomed in or out, it either doesn't move or another piece of clothing / accessory is dragged instead.

Steps to reproduce:
1. Set the page zoom to 150%.
2. Try dragging the army shorts (upper right) in set 8.
![army](https://user-images.githubusercontent.com/17948023/27260438-6c05d9be-53fa-11e7-8ed5-138e37a07fc1.png)

Actual result: Depending on the mouse position, one of the short sleeve tops is dragged.
![ham](https://user-images.githubusercontent.com/17948023/27260495-772f6944-53fb-11e7-8a7a-37cb2f4cb6ad.png) ![fruit](https://user-images.githubusercontent.com/17948023/27260496-7aec62da-53fb-11e7-8a5b-f3ad23c94d13.png)

Expected result: The army shorts is dragged.

**Comment by emhoracek** [comment]
@huggablemonad thanks for opening this issue. I'm focusing on getting the dolls to work in Firefox and Chrome first but once I've got the first KiSS spec working in those I'll take a look at this again. I also welcome PRs if you would be interested in investigating what's going on!

**Comment by emhoracek** [comment]
@huggablemonad I'm not sure, but this may be fixed now? I was using a web api that wasn't very well supported, and now I'm using a more supported one. So click registration may work better with your browser.

**Comment by huggablemonad** [comment]
No problems with the example sets, so I'd say it's fixed! :smile:

**Comment by emhoracek** [comment]
@huggablemonad that's great!
