### ISSUE TITLE
Redirect users to their user page on login

### ISSUE THREAD

**Issue by emhoracek** [emhoracek/smooch#44]
Right now, when a user logs in, they just see some text that says "insert-username-here is logged in!". Instead, the user should be redirected to the page where they can see sets that they have uploaded and upload a new set.

To do this, you'll change line 78 of the `Web.hs` module from:

```okText (userUsername user <> " is logged in!")```

to 

```redirect ("/users/" <> username)```

Although this is a very small change, testing it will require [setting up the app on your computer](https://github.com/emhoracek/smooch/blob/master/CONTRIBUTING.md#run-smooch-on-your-computer). I'm happy to assist you with getting it set up, but it could take a few hours. Please take that into account when claiming this issue.

This is a "first-timers-only" task. If you have never contributed to an open source project, you can work on this issue and I will help you through the process. If you've contributed to *any* OSS project before, please leave this issue for someone else.

**Comment by 42flyingfish** [comment]
I would like to give this a try.

**Comment by emhoracek** [comment]
Hi @42flyingfish! The first thing you'll want to do is fork the project to your own account, and clone the project. Then get the project running on your computer. Follow the instructions I link to in the issue description above. Let me know if you run into any trouble with any part of this process.

**Comment by 42flyingfish** [comment]
I seem to be having an issue with running the application myself. After following the steps on Arch Linux, I am getting 
`smooch: ENV: getEnv: does not exist (no environment variable)
`
Do you have any suggestions?

**Comment by emhoracek** [comment]
Yes! Sorry, I forgot to add that to the instructions. Try `ENV=devel stack exec smooch`.

**Comment by 42flyingfish** [comment]
Thank you, that did the trick. I think that I am ready to make my first pull request.
