### ISSUE TITLE
Allow users to logout

### ISSUE THREAD

**Issue by emhoracek** [emhoracek/smooch#46]
Users should be able to log out of their account.

Add a `/logout` endpoint that logs a user out. This will probably require a new function like `setLoggedInUser` that unsets the "user" session key. Unfortunately, allowing us to unset a value will mean changing the type of the session store! Why? Sessions only provide two functions: a lookup function, and an *insert* function. There is no delete function! So, the way to "unset" a key is to set the value to `Nothing`. So we need our `SessionStore` to be not a `Map` from `Text` to `Text` (like it currently is) but a map from `Text` to `Maybe Text`.

Steps:

1. Add a route for "/logout" in `routes` in `Web.hs`. The order of routes matters -- it should be right below the "/login" route. This route should be a `POST`, but unlike "/login", it doesn't need any parameters.
2. Add a handler function for the route to `Web.hs`. The handler should be something like `logoutHandler` and it should have the type `Ctxt -> IO (Maybe Response)`. 
3. Add a function to `User/Model.hs` that calls a function that unsets the "user" session key.
4. Change the type of the session store to a `Map Text (Maybe Text)`.

**Comment by astynax** [comment]
Can I take it?

**Comment by emhoracek** [comment]
@astynax Sure! Let me know if you run into any problems.
