### ISSUE TITLE
Make it so that ghost canvas can handle more than 255 items

### ISSUE THREAD

**Issue by jarmstrng** [emhoracek/smooch#59]
https://github.com/emhoracek/smooch/blob/f0097918ffefb78dc3fda316b53acbcdd52d91f2/javascript/doll.js#L76

TODO: Handle ids larger than 255
Need to map each integer to a unique color

Sometimes dolls have more than 255 items, and currently those extra items aren't assigned a color in the ghost canvas.

In fixing this, we need to make sure multiple items are not assigned the same color.

**Comment by MariaVolpe** [comment]
I'm going to give it a shot!

**Comment by emhoracek** [comment]
@MariaVolpe Excited to see your solution!
