### ISSUE TITLE
Remove unused variable

### ISSUE THREAD

**Issue by jarmstrng** [emhoracek/smooch#60]
https://github.com/emhoracek/smooch/blob/f0097918ffefb78dc3fda316b53acbcdd52d91f2/javascript/doll.js#L382

It appears this `blah` variable isn't being used anywhere

**Comment by Neidley** [comment]
May I claim this issue?

**Comment by emhoracek** [comment]
@Neidley Thanks so much for asking, but we were creating issues for a workshop tonight. Please check in again tomorrow? If no one has claimed it by then, then definitely. There may also be more interesting issues added by workshop attendees.

**Comment by erinfox** [comment]
claim :)
