### ISSUE TITLE
Make it so clicking on doll name locally goes directly to doll's /index.html

### ISSUE THREAD

**Issue by jarmstrng** [emhoracek/smooch#63]
When working locally, clicking on the name of a doll takes you to the folder, and then you must click on the index.html file from there to get to the doll's page (it works fine on the hosted homepage because GitHub automatically serves index files under `/docs`).

It would be a nicer workflow for us if the doll links in `file:///Users/<local path>/smooch/docs/index.html` went directly to the doll's index.html page.

**Comment by emhoracek** [comment]
Thanks @jarmstrng! Just want to add that this problem is in the `/docs/index.html` file.

**Comment by cassiemoy** [comment]
Can we claim this? 😸
