### ISSUE TITLE
Link to GitHub repo in footer should open in a new tab

### ISSUE THREAD

**Issue by jarmstrng** [emhoracek/smooch#64]
Currently, the link in the screen shot below opens in the same tab. 

Dress-up doll enthusiasts probably would prefer to keep the doll they've been playing with in the same tab while perusing the source code in a new tab.

<img width="642" alt="screen shot 2018-07-18 at 1 54 11 pm" src="https://user-images.githubusercontent.com/7620750/42898826-42216ce2-8a92-11e8-9853-d2002d09af28.png">

**Comment by emhoracek** [comment]
Agreed! This change should be made to the `javascript/kiss.html` file and tested visually in a browser. Once it works, copy the code to the `app/templates/kissSet.tpl` template so that the actual app will work the same way.

**Comment by aariasgonz21** [comment]
Got it!
