### ISSUE TITLE
Remove unused variable & attribute

### ISSUE THREAD

**Issue by jarmstrng** [emhoracek/smooch#65]
https://github.com/emhoracek/smooch/blob/20bd5286c7fa9c0da3d1c9c822fa68c1e5b6bb04/javascript/doll.js#L8-L10

Looks like `editMode` and `editButton` never get used. Please remove them.

**Comment by Neidley** [comment]
May I claim this issue?

**Comment by Shadow2xx** [comment]
Is it normal to add this one as an issue instead just making a pull request?

**Comment by Jengel1** [comment]
Not sure if this issue has been claimed but I'd love to work on it.

**Comment by Jengel1** [comment]
Tried to push my changes but received 403 error.

remote: Permission to emhoracek/smooch.git denied to Jengel1.
fatal: unable to access "https://github.com/emhoracek/smooch/"

Does anyone have any advice?

**Comment by hernandesdoug** [comment]
Can I work in this issue? I'm new here.

**Comment by emhoracek** [comment]
@Shadow2xx This is an issue specifically for people who are brand-new to open source so they can get their feet wet with a very easy issue.

**Comment by hernandesdoug** [comment]
I'm brand new to open source. I'm finishing a course at Udacity and I would like to have some practice.
