### ISSUE TITLE
`Kiss.hs` fails to compile (duplicate field label `kCels`)

### ISSUE THREAD

**Issue by huggablemonad** [emhoracek/smooch#79]
Do you want to request a feature or report a bug?

Bug.

What is the current behavior?

`Kiss.hs` fails to compile on the master branch (436c673b29afa7212a692b8cc40ed4e4637457ae):

```haskell
/home/huggablemonad/projects/smooch/app/src/Kiss.hs:21:28: error:
    Multiple declarations of ‘kCels’
    Declared at: src/Kiss.hs:9:26
                 src/Kiss.hs:21:28
```

What is the expected behavior?

There shouldn't be any compilation errors.

Which browser / OS are affected by this issue?

All.

**Comment by emhoracek** [comment]
@huggablemonad Thanks for catching this! Somehow I missed it when I was testing #78.
