### ISSUE TITLE
"Violet" by Alison and Hm (2002)

### ISSUE THREAD

**Issue by emhoracek** [emhoracek/smooch#8]
Seems to be a missing some background images, or they're in the wrong places? The background should look like this: 

![screen shot 2017-08-07 at 6 19 49 pm](https://user-images.githubusercontent.com/5353499/29048106-0ae45672-7b9d-11e7-8672-8c3b692c3b16.png)

Everything else seems to look okay about this set.

On OtakuWorld: http://otakuworld.com/kiss/dolls/pages/v/violetah.htm

**Comment by huggablemonad** [comment]
I think the tussle between cels 4-8 for the position of a single `bg.png` causes the background to cover only part of the play area.

With these changes to `violet.cnf`:

```
#5.9999 bg5.cel *0 :0 1 2 3 4 5 6 7 8 9
#4.9999 bg4.cel *0 :0 1 2 3 4 5 6 7 8 9
#7.9999 bg7.cel *0 :0 1 2 3 4 5 6 7 8 9
#8.9999 bg8.cel *0 :0 1 2 3 4 5 6 7 8 9
#6.9999 bg6.cel *0 :0 1 2 3 4 5 6 7 8 9
```
And after linking `bg{4,5,6,7,8}.cel` to `bg.cel` (I changed the background colors of `bg{4,5,6,7,8}.png` so I can see it more clearly):

![violetah-background-test](https://user-images.githubusercontent.com/17948023/29462991-acbe5230-8463-11e7-979b-c6b5781ddb41.png)

**Comment by emhoracek** [comment]
@huggablemonad Yay this is so helpful! That's exactly what it was. The script was trying to match up the object to the cel by name, so even though there are 5 copies of the cel and 5 objects, all the objects were just using the first cel with that name. I changed this to not reassign cels that already belonged to an object.

Now it just looks like a cel transparency problem.

<img width="812" alt="screen shot 2017-08-19 at 11 34 05 am" src="https://user-images.githubusercontent.com/5353499/29488126-5d4256f6-84d2-11e7-8af8-5d12192eb79c.png">

**Comment by huggablemonad** [comment]
It seems that prefixing `=` to the transparent color fixes the problem, e.g., `=rgb:ff/f7/ff`. Here's the explanation for `-transparent color` from the `pnmtopng` man page:

> If the color you specify is not present in the image, `pnmtopnm` [sic] selects instead the color in the image  that  is closest to the one you specify.
> ...
> However, if you prefix your color specification with "=", e.g.
> ` -transparent =red`
> Only  the  exact  color  you  specify will be transparent. If that color does not appear in the image, there will be no transparency.

![violetah-background-ok](https://user-images.githubusercontent.com/17948023/29494682-1b60fdd0-85e2-11e7-892d-50597adf6227.png)

However, the blood stain behind the hat (`hat.cel`) is missing. I'm not sure but it could be a layering issue because the background doesn't quite look the same.

**Comment by emhoracek** [comment]
@huggablemonad Thanks so much -- that transparency thing has probably been causing a lot of problems! You're right about there being a layering problem -- I think that has to do with how I tried to fix the multiple objects-one cel problem. So still some work to do there!

**Comment by emhoracek** [comment]
Finally found a way to fix this one, although I'm still not exactly sure what was wrong. I moved the object grouping logic to the frontend and in the process this bug was fixed.

<img width="826" alt="Screen Shot 2022-02-21 at 3 44 51 PM" src="https://user-images.githubusercontent.com/5353499/155024206-b3e1fc6d-054a-4dfd-a897-4b71fecedc8d.png">
